# Data Science Project 1: Data Wrangling Practical
**Duration:** 1 Hour, 15 Minutes  
**Format:** Open-notes code implementation (Python/Pandas)

### **Project Scenario**
You have been given a raw slice of **Glassdoor Data Science Job Postings**. The dataset contains a variety of small errors, missing variables, and split locations. Your goal is to clean this main dataset, create engineered features, and merge it with a regional mapping file so the analytics team can use it.

## Load the data
Download the data from the Blackboard to your computer frist, then load your libraries and the datasets required for this exam here.

In [89]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

dfJobs = pd.read_csv('glassdoor_jobs.csv')
dfRegions = pd.read_csv('state_regions.csv')

## Part 1: Missing Data & Filtering (30 Points)

### **Task 1.1 (Standardizing Nulls)**
The `Rating` column represents missing values as `-1`. Replace all occurrences of `-1` with the dataset's overall **average (mean)** rating value.

In [90]:
# dfJobs
dfJobRatingAvg = dfJobs['Rating'].mean()
dfJobs['Rating'] = dfJobs['Rating'].replace(-1.0, dfJobRatingAvg).round(1)
dfJobs

,Job_Title,Job Description,Rating,Company_Name,Location,Founded,Industry
0,Sr Data Scientist,Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst\n3.1,"New York, NY",1993,Insurance Carriers
1,Data Scientist,"Secure our Nation, Ignite your Future\n\nJoin ...",4.2,ManTech\n4.2,"Chantilly, VA",1968,Research & Development
2,Data Scientist,Overview\n\n\nAnalysis Group is one of the lar...,3.0,Analysis Group\n3.8,"Boston, MA",1981,Consulting
3,Data Scientist,JOB DESCRIPTION:\n\nDo you have a passion for ...,3.5,INFICON\n3.5,"Newton, MA",2000,Electrical & Electronic Manufacturing
4,Data Scientist,Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,"New York, NY",1998,Advertising & Marketing
...,...,...,...,...,...,...,...
667,Data Scientist,Summary\n\nWe’re looking for a data scientist ...,3.0,TRANZACT\n3.6,"Fort Lee, NJ",1989,Advertising & Marketing
668,Data Scientist,Job Description\nBecome a thought leader withi...,3.0,JKGT,"San Francisco, CA",-1,-1
669,Data Scientist,Join a thriving company that is changing the w...,3.0,AccessHope,"Irwindale, CA",-1,-1
670,Data Scientist,100 Remote Opportunity As an AINLP Data Scient...,5.0,ChaTeck Incorporated\n5.0,"San Francisco, CA",-1,Advertising & Marketing
671,Data Scientist,Description\n\nThe Data Scientist will be part...,2.7,1-800-Flowers\n2.7,"New York, NY",1976,Wholesale

### **Task 1.2 (Handling Blanks)**
The `Industry` column has several completely blank or empty cells. Fill these missing values with the string text `"Unknown"`.

In [91]:
dfJobs['Industry'] = dfJobs['Industry'].replace('-1', 'Unknown')
dfJobs

,Job_Title,Job Description,Rating,Company_Name,Location,Founded,Industry
0,Sr Data Scientist,Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst\n3.1,"New York, NY",1993,Insurance Carriers
1,Data Scientist,"Secure our Nation, Ignite your Future\n\nJoin ...",4.2,ManTech\n4.2,"Chantilly, VA",1968,Research & Development
2,Data Scientist,Overview\n\n\nAnalysis Group is one of the lar...,3.0,Analysis Group\n3.8,"Boston, MA",1981,Consulting
3,Data Scientist,JOB DESCRIPTION:\n\nDo you have a passion for ...,3.5,INFICON\n3.5,"Newton, MA",2000,Electrical & Electronic Manufacturing
4,Data Scientist,Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,"New York, NY",1998,Advertising & Marketing
...,...,...,...,...,...,...,...
667,Data Scientist,Summary\n\nWe’re looking for a data scientist ...,3.0,TRANZACT\n3.6,"Fort Lee, NJ",1989,Advertising & Marketing
668,Data Scientist,Job Description\nBecome a thought leader withi...,3.0,JKGT,"San Francisco, CA",-1,Unknown
669,Data Scientist,Join a thriving company that is changing the w...,3.0,AccessHope,"Irwindale, CA",-1,Unknown
670,Data Scientist,100 Remote Opportunity As an AINLP Data Scient...,5.0,ChaTeck Incorporated\n5.0,"San Francisco, CA",-1,Advertising & Marketing
671,Data Scientist,Description\n\nThe Data Scientist will be part...,2.7,1-800-Flowers\n2.7,"New York, NY",1976,Wholesale

### **Task 1.3 (Data Filtering)**
A few rows contain placeholder or invalid values in the `Founded` year column (values less than or equal to `0`). **Filter the dataset** to permanently remove these invalid rows.

In [92]:
dfJobs = dfJobs[dfJobs['Founded'] >= 0]
dfJobs

,Job_Title,Job Description,Rating,Company_Name,Location,Founded,Industry
0,Sr Data Scientist,Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst\n3.1,"New York, NY",1993,Insurance Carriers
1,Data Scientist,"Secure our Nation, Ignite your Future\n\nJoin ...",4.2,ManTech\n4.2,"Chantilly, VA",1968,Research & Development
2,Data Scientist,Overview\n\n\nAnalysis Group is one of the lar...,3.0,Analysis Group\n3.8,"Boston, MA",1981,Consulting
3,Data Scientist,JOB DESCRIPTION:\n\nDo you have a passion for ...,3.5,INFICON\n3.5,"Newton, MA",2000,Electrical & Electronic Manufacturing
4,Data Scientist,Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,"New York, NY",1998,Advertising & Marketing
...,...,...,...,...,...,...,...
663,Data Scientist,Job Description\nEducation and Experience:\nAt...,4.1,A-Line Staffing Solutions\n4.1,"Durham, NC",2004,Staffing & Outsourcing
665,Data Scientist,Criterion Systems seeks a Data Scientist to su...,3.8,"Criterion Systems, Inc.\n3.8","Vienna, VA",2005,IT Services
666,Data Scientist,About Foundation Medicine:\n\nFoundation Medic...,4.0,Foundation Medicine\n4.0,"Boston, MA",2010,Biotech & Pharmaceuticals
667,Data Scientist,Summary\n\nWe’re looking for a data scientist ...,3.0,TRANZACT\n3.6,"Fort Lee, NJ",1989,Advertising & Marketing
671,Data Scientist,Description\n\nThe Data Scientist will be part...,2.7,1-800-Flowers\n2.7,"New York, NY",1976,Wholesale

## Part 2: String Manipulations (20 Points)

### **Task 2.1 (Location Splitting)**
The `Location` column lists locations as `"City, State"` (e.g., `"Chicago, IL"` or `"Austin, TX"`). Split this column into two separate, brand-new columns: `Job_City` and `Job_State`.

In [93]:
dfJobs[['Job_City', 'Job_State']] = dfJobs['Location'].str.split(', ', n=1 , expand=True)
dfJobs = dfJobs.drop(columns = ['Location'])
dfJobs

,Job_Title,Job Description,Rating,Company_Name,Founded,Industry,Job_City,Job_State
0,Sr Data Scientist,Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst\n3.1,1993,Insurance Carriers,New York,NY
1,Data Scientist,"Secure our Nation, Ignite your Future\n\nJoin ...",4.2,ManTech\n4.2,1968,Research & Development,Chantilly,VA
2,Data Scientist,Overview\n\n\nAnalysis Group is one of the lar...,3.0,Analysis Group\n3.8,1981,Consulting,Boston,MA
3,Data Scientist,JOB DESCRIPTION:\n\nDo you have a passion for ...,3.5,INFICON\n3.5,2000,Electrical & Electronic Manufacturing,Newton,MA
4,Data Scientist,Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,1998,Advertising & Marketing,New York,NY
...,...,...,...,...,...,...,...,...
663,Data Scientist,Job Description\nEducation and Experience:\nAt...,4.1,A-Line Staffing Solutions\n4.1,2004,Staffing & Outsourcing,Durham,NC
665,Data Scientist,Criterion Systems seeks a Data Scientist to su...,3.8,"Criterion Systems, Inc.\n3.8",2005,IT Services,Vienna,VA
666,Data Scientist,About Foundation Medicine:\n\nFoundation Medic...,4.0,Foundation Medicine\n4.0,2010,Biotech & Pharmaceuticals,Boston,MA
667,Data Scientist,Summary\n\nWe’re looking for a data scientist ...,3.0,TRANZACT\n3.6,1989,Advertising & Marketing,Fort Lee,NJ
671,Data Scientist,Description\n\nThe Data Scientist will be part...,2.7,1-800-Flowers\n2.7,1976,Wholesale,New York,NY

### **Task 2.2 (Whitespace Cleaning)**
The new `Job_State` column might contain accidental leading or trailing empty spaces from the split. Apply a string cleaning function (like `.str.strip()`) to ensure no accidental spaces remain.

In [94]:
dfJobs['Job_State'] = dfJobs['Job_State'].str.strip()
dfJobs['Job_City'] = dfJobs['Job_City'].str.strip()
dfJobs

,Job_Title,Job Description,Rating,Company_Name,Founded,Industry,Job_City,Job_State
0,Sr Data Scientist,Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst\n3.1,1993,Insurance Carriers,New York,NY
1,Data Scientist,"Secure our Nation, Ignite your Future\n\nJoin ...",4.2,ManTech\n4.2,1968,Research & Development,Chantilly,VA
2,Data Scientist,Overview\n\n\nAnalysis Group is one of the lar...,3.0,Analysis Group\n3.8,1981,Consulting,Boston,MA
3,Data Scientist,JOB DESCRIPTION:\n\nDo you have a passion for ...,3.5,INFICON\n3.5,2000,Electrical & Electronic Manufacturing,Newton,MA
4,Data Scientist,Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,1998,Advertising & Marketing,New York,NY
...,...,...,...,...,...,...,...,...
663,Data Scientist,Job Description\nEducation and Experience:\nAt...,4.1,A-Line Staffing Solutions\n4.1,2004,Staffing & Outsourcing,Durham,NC
665,Data Scientist,Criterion Systems seeks a Data Scientist to su...,3.8,"Criterion Systems, Inc.\n3.8",2005,IT Services,Vienna,VA
666,Data Scientist,About Foundation Medicine:\n\nFoundation Medic...,4.0,Foundation Medicine\n4.0,2010,Biotech & Pharmaceuticals,Boston,MA
667,Data Scientist,Summary\n\nWe’re looking for a data scientist ...,3.0,TRANZACT\n3.6,1989,Advertising & Marketing,Fort Lee,NJ
671,Data Scientist,Description\n\nThe Data Scientist will be part...,2.7,1-800-Flowers\n2.7,1976,Wholesale,New York,NY

## Part 3: Feature Engineering with Grouped Transformations (20 Points)

### **Task 3.1 (Grouped Transform)**
The recruiting team wants to identify jobs that offer a higher-than-average user rating relative to their specific field. 

Use `.groupby()` and `.transform()` to calculate the **average (mean) rating for each `Industry`**, broadcasting it back as a new column named `Industry_Avg_Rating`. Then, create a column called `Rating_Above_Industry_Avg` by subtracting `Industry_Avg_Rating` from the job's original `Rating`.

In [95]:
dfJobs['Industry_Avg_Rating'] = dfJobs.groupby('Industry')['Rating'].transform('mean').round(2)
dfJobs['Rating_Above_Industry_Avg'] = dfJobs['Rating'] - dfJobs['Industry_Avg_Rating']
dfJobs

,Job_Title,Job Description,Rating,Company_Name,Founded,Industry,Job_City,Job_State,Industry_Avg_Rating,Rating_Above_Industry_Avg
0,Sr Data Scientist,Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst\n3.1,1993,Insurance Carriers,New York,NY,3.55,-0.45
1,Data Scientist,"Secure our Nation, Ignite your Future\n\nJoin ...",4.2,ManTech\n4.2,1968,Research & Development,Chantilly,VA,3.79,0.41
2,Data Scientist,Overview\n\n\nAnalysis Group is one of the lar...,3.0,Analysis Group\n3.8,1981,Consulting,Boston,MA,3.64,-0.64
3,Data Scientist,JOB DESCRIPTION:\n\nDo you have a passion for ...,3.5,INFICON\n3.5,2000,Electrical & Electronic Manufacturing,Newton,MA,3.25,0.25
4,Data Scientist,Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,1998,Advertising & Marketing,New York,NY,3.54,-0.64
...,...,...,...,...,...,...,...,...,...,...
663,Data Scientist,Job Description\nEducation and Experience:\nAt...,4.1,A-Line Staffing Solutions\n4.1,2004,Staffing & Outsourcing,Durham,NC,4.00,0.10
665,Data Scientist,Criterion Systems seeks a Data Scientist to su...,3.8,"Criterion Systems, Inc.\n3.8",2005,IT Services,Vienna,VA,4.06,-0.26
666,Data Scientist,About Foundation Medicine:\n\nFoundation Medic...,4.0,Foundation Medicine\n4.0,2010,Biotech & Pharmaceuticals,Boston,MA,3.62,0.38
667,Data Scientist,Summary\n\nWe’re looking for a data scientist ...,3.0,TRANZACT\n3.6,1989,Advertising & Marketing,Fort Lee,NJ,3.54,-0.54
671,Data Scientist,Description\n\nThe Data Scientist will be part...,2.7,1-800-Flowers\n2.7,1976,Wholesale,New York,NY,2.63,0.07

## Part 4: Merging & Aggregating Data (30 Points)

### **Task 4.1 (Dataset Merging)**
You are provided a second, clean reference CSV file named `state_regions.csv` which contains two columns: `State_Abbreviation` and `US_Region` (e.g., *IL, Midwest*). 

Perform a **left merge** to add the `US_Region` column to your main job postings dataframe by matching your new `Job_State` column with the reference file's `State_Abbreviation` column.

In [96]:
dfRegions
mergedDf = pd.merge(dfJobs, dfRegions, left_on='Job_State', right_on='State_Abbreviation', how='inner')
mergedDf = mergedDf.drop(columns='State_Abbreviation')
mergedDf

,Job_Title,Job Description,Rating,Company_Name,Founded,Industry,Job_City,Job_State,Industry_Avg_Rating,Rating_Above_Industry_Avg,US_Region
0,Sr Data Scientist,Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst\n3.1,1993,Insurance Carriers,New York,NY,3.55,-0.45,Northeast
1,Data Scientist,"Secure our Nation, Ignite your Future\n\nJoin ...",4.2,ManTech\n4.2,1968,Research & Development,Chantilly,VA,3.79,0.41,South
2,Data Scientist,Overview\n\n\nAnalysis Group is one of the lar...,3.0,Analysis Group\n3.8,1981,Consulting,Boston,MA,3.64,-0.64,Northeast
3,Data Scientist,JOB DESCRIPTION:\n\nDo you have a passion for ...,3.5,INFICON\n3.5,2000,Electrical & Electronic Manufacturing,Newton,MA,3.25,0.25,Northeast
4,Data Scientist,Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,1998,Advertising & Marketing,New York,NY,3.54,-0.64,Northeast
...,...,...,...,...,...,...,...,...,...,...,...
352,Senior Data Scientist,"About Us\n\nAt GutCheck, we pioneered agile ma...",3.0,GutCheck\n3.8,2009,Advertising & Marketing,Denver,CO,3.54,-0.54,West
353,Sr. ML/Data Scientist - AI/NLP/Chatbot,Sr. ML/Data Scientist - AI/NLP/Chatbot\n\nMist...,3.8,Juniper Networks\n3.8,1996,Telecommunications Services,Cupertino,CA,3.24,0.56,West
354,Data Scientist,Criterion Systems seeks a Data Scientist to su...,3.8,"Criterion Systems, Inc.\n3.8",2005,IT Services,Vienna,VA,4.06,-0.26,South
355,Data Scientist,About Foundation Medicine:\n\nFoundation Medic...,4.0,Foundation Medicine\n4.0,2010,Biotech & Pharmaceuticals,Boston,MA,3.62,0.38,Northeast
356,Data Scientist,Description\n\nThe Data Scientist will be part...,2.7,1-800-Flowers\n2.7,1976,Wholesale,New York,NY,2.63,0.07,Northeast

### **Task 4.2 (Grouped Aggregation)**
Group your newly merged dataframe by the `US_Region` column. For each region, calculate:
1. The **total count** of job postings in that region.
2. The **average (mean)** employee `Rating` in that region.

In [97]:
mergedDf['Region_Job_Count'] = mergedDf.groupby('US_Region')['Job_Title'].transform('count')
mergedDf['Region_Avg_Rating'] = mergedDf.groupby('US_Region')['Rating'].transform('mean').round(2)
mergedDf

,Job_Title,Job Description,Rating,Company_Name,Founded,Industry,Job_City,Job_State,Industry_Avg_Rating,Rating_Above_Industry_Avg,US_Region,Region_Job_Count,Region_Avg_Rating
0,Sr Data Scientist,Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst\n3.1,1993,Insurance Carriers,New York,NY,3.55,-0.45,Northeast,99,3.85
1,Data Scientist,"Secure our Nation, Ignite your Future\n\nJoin ...",4.2,ManTech\n4.2,1968,Research & Development,Chantilly,VA,3.79,0.41,South,85,3.89
2,Data Scientist,Overview\n\n\nAnalysis Group is one of the lar...,3.0,Analysis Group\n3.8,1981,Consulting,Boston,MA,3.64,-0.64,Northeast,99,3.85
3,Data Scientist,JOB DESCRIPTION:\n\nDo you have a passion for ...,3.5,INFICON\n3.5,2000,Electrical & Electronic Manufacturing,Newton,MA,3.25,0.25,Northeast,99,3.85
4,Data Scientist,Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,1998,Advertising & Marketing,New York,NY,3.54,-0.64,Northeast,99,3.85
...,...,...,...,...,...,...,...,...,...,...,...,...,...
352,Senior Data Scientist,"About Us\n\nAt GutCheck, we pioneered agile ma...",3.0,GutCheck\n3.8,2009,Advertising & Marketing,Denver,CO,3.54,-0.54,West,147,3.74
353,Sr. ML/Data Scientist - AI/NLP/Chatbot,Sr. ML/Data Scientist - AI/NLP/Chatbot\n\nMist...,3.8,Juniper Networks\n3.8,1996,Telecommunications Services,Cupertino,CA,3.24,0.56,West,147,3.74
354,Data Scientist,Criterion Systems seeks a Data Scientist to su...,3.8,"Criterion Systems, Inc.\n3.8",2005,IT Services,Vienna,VA,4.06,-0.26,South,85,3.89
355,Data Scientist,About Foundation Medicine:\n\nFoundation Medic...,4.0,Foundation Medicine\n4.0,2010,Biotech & Pharmaceuticals,Boston,MA,3.62,0.38,Northeast,99,3.85
356,Data Scientist,Description\n\nThe Data Scientist will be part...,2.7,1-800-Flowers\n2.7,1976,Wholesale,New York,NY,2.63,0.07,Northeast,99,3.85

### **Task 4.3 (Data Export)**
Save your final, aggregated summary table from Task 4.2 to a new file named `regional_job_summary.csv`.

In [98]:
mergedDf.to_csv('regional_job_summary.csv', index=False)
outputDf = pd.read_csv('regional_job_summary.csv')
outputDf

,Job_Title,Job Description,Rating,Company_Name,Founded,Industry,Job_City,Job_State,Industry_Avg_Rating,Rating_Above_Industry_Avg,US_Region,Region_Job_Count,Region_Avg_Rating
0,Sr Data Scientist,Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst\n3.1,1993,Insurance Carriers,New York,NY,3.55,-0.45,Northeast,99,3.85
1,Data Scientist,"Secure our Nation, Ignite your Future\n\nJoin ...",4.2,ManTech\n4.2,1968,Research & Development,Chantilly,VA,3.79,0.41,South,85,3.89
2,Data Scientist,Overview\n\n\nAnalysis Group is one of the lar...,3.0,Analysis Group\n3.8,1981,Consulting,Boston,MA,3.64,-0.64,Northeast,99,3.85
3,Data Scientist,JOB DESCRIPTION:\n\nDo you have a passion for ...,3.5,INFICON\n3.5,2000,Electrical & Electronic Manufacturing,Newton,MA,3.25,0.25,Northeast,99,3.85
4,Data Scientist,Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,1998,Advertising & Marketing,New York,NY,3.54,-0.64,Northeast,99,3.85
...,...,...,...,...,...,...,...,...,...,...,...,...,...
352,Senior Data Scientist,"About Us\n\nAt GutCheck, we pioneered agile ma...",3.0,GutCheck\n3.8,2009,Advertising & Marketing,Denver,CO,3.54,-0.54,West,147,3.74
353,Sr. ML/Data Scientist - AI/NLP/Chatbot,Sr. ML/Data Scientist - AI/NLP/Chatbot\n\nMist...,3.8,Juniper Networks\n3.8,1996,Telecommunications Services,Cupertino,CA,3.24,0.56,West,147,3.74
354,Data Scientist,Criterion Systems seeks a Data Scientist to su...,3.8,"Criterion Systems, Inc.\n3.8",2005,IT Services,Vienna,VA,4.06,-0.26,South,85,3.89
355,Data Scientist,About Foundation Medicine:\n\nFoundation Medic...,4.0,Foundation Medicine\n4.0,2010,Biotech & Pharmaceuticals,Boston,MA,3.62,0.38,Northeast,99,3.85
356,Data Scientist,Description\n\nThe Data Scientist will be part...,2.7,1-800-Flowers\n2.7,1976,Wholesale,New York,NY,2.63,0.07,Northeast,99,3.85